### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by matheustavaresdev** [Jyouya/AngeAI#1]
I have pasted on my `AI` folder and then had to create an `USER_AI` folder with everything duplicated inside, but my Vanilmirth will only go around in circles around me and melee attack monsters... Not sure if I'm missing something for him to use skills..

**Comment by matheustavaresdev** [comment]
Seems that homunculus wont use skills anymore... :/ https://forums.warpportal.com/index.php?/topic/246709-homunculus-ai-dont-work/

**Comment by Jyouya** [comment]
Homs work differently on the latest clients, but many servers use older clients or patch it to use the AI still.  If it's circling around you and attacking mobs, that means the AI is working, but is unable to use skills for some reason.  The AI was designed for a specific server with moderately customized homunculi, so you may need to edit the skill durations, cooldowns, and sp costs to match your server, as that could potentially be causing the issue.  Also, in the case that you have a low level homunculus, double check that it has enough sp to cast the spells at max level.
